name: Run Table Script

on:
  push:
    branches:
      - main

jobs:
  run_table_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Debug Information
        run: |
          echo "Current working directory: $PWD"
          ls -al

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ${{ github.workspace }}

      - name: Run Table Script
        run: python table.py
        working-directory: ${{ github.workspace }}

